x = input('Digite uma nome:')
print(f'O tipo primitivo dessa variável é', type(x))
print('Ela é um número?', x.isnumeric())
print('É maiúsculo', x.isupper())
print('É minúsculo', x.islower())
print('É capitalizado', x.istitle())
print('É alfabético', x.isalpha())
print('É alfanumérico', x.isalnum())
print('Só tem espaço?', x.isspace())
